### ISSUE TITLE
list of not completed students

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#100]
in grafana, get a list of not completed students.

**Comment by mohamednizar** [comment]
@anjilo27 , Please start working on another panel which we could be able to get the list of student's as in the description.

**Comment by nshamit** [comment]
@anjilo27 to follow up. 
validate against whether all fields have been filled.

**Comment by jeewana20** [comment]
the schools must get an excel sheet where the students' other details such as subjects, special needs and guardian details are not filled.

**Comment by jeewana20** [comment]
this can be fulfilled by #93

**Comment by anjilo27** [comment]
@mohamednizar We have the students all details query and how can we get the empty fields and show those details from all student details query.
