### ISSUE TITLE
Bulk upload - students count exceeded 

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#102]
in the bulk upload the sheet is rejected although the total student no for the class equals the no stated in the class

**Comment by nshamit** [comment]
@jeewana20 to provide more information

**Comment by jeewana20** [comment]
for example, the student count is set to 40. and if you are going to upload 40 students through bulk upload the system rejects stating the that the student count has exceeded. when they delete 5 students from the sheet it was successfully uploaded. then they increase the class count to 45 then they again upload the 5 students previously deleted. then they were able to upload the 5 students.

**Comment by mohamednizar** [comment]
@jeewana20 , can we confirm that the issue is relay existing in the system ? or the users mistaken the process?

**Comment by jeewana20** [comment]
no cases found
