### ISSUE TITLE
Missing Controller

### ISSUE THREAD

**Issue by Fuseteam** [moe-lk/sis-php#136]
i cloned the repo into my webroot and assessed it via the browser under "localhost/sis/php"
i am greeted with an error `Error: sis-phpController could not be found`

i have tried creating the file in  src/Controller/sis-phpController.php
but still the same error
please advise

**Comment by mohamednizar** [comment]
@Fuseteam ,  try out our docker setup for start working with the project. https://github.com/moe-lk/sis. You would be able start the project run by docker-compose up.

Else you need follow the configuration for cakephp in apache2. copy  the https://github.com/moe-lk/sis-php/blob/master/apache_default to your apache2 config folder and refer the webroot in the line of 16 and 17.

**Comment by Fuseteam** [comment]
thanks, indeed that seems to have solved that error
but now i get this error:`Cache engine Cake\Cache\Engine\FileEngine is not properly configured. ` , should i open a new issue about it?

**Comment by Fuseteam** [comment]
update:
i found out i had to do this command
```
HTTPDUSER=`ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
sudo setfacl -R -m u:${HTTPDUSER}:rwx tmp
sudo setfacl -R -d -m u:${HTTPDUSER}:rwx tmp
sudo setfacl -R -m u:${HTTPDUSER}:rwx logs
sudo setfacl -R -d -m u:${HTTPDUSER}:rwx logs
```

**Comment by Fuseteam** [comment]
closing issue as the original issue is solved
