### ISSUE TITLE
missing table themes

### ISSUE THREAD

**Issue by Fuseteam** [moe-lk/sis-php#138]
after correctly setting up the database connection i get the error "table themes does not exist" as the database it's connecting to is brand new it does not contain any tables at the moment.
Please advise how to get the application to set the tables it needs up

**Comment by mohamednizar** [comment]
@Fuseteam , log in to you Mysql instance and check if it has a database call OpenEMIS, Use Mysql workbench for it.

**Comment by Fuseteam** [comment]
@mohamednizar it does the database need that exact name? otherwise a database called "openemis" does exist, it doesn't contain any tables however

**Comment by mohamednizar** [comment]
@Fuseteam than import the DB from https://github.com/moe-lk/sis/tree/master/mysql/Dump20190205 and run `bash build.sh` in the application root folder.

**Comment by Fuseteam** [comment]
@mohamednizar does that script import the db? there seems to be a lot of sql files i missed.....

**Comment by janithRS** [comment]
@Fuseteam  https://github.com/moe-lk/sis/tree/master/mysql/Dump20190205 Use this dump to import data tables (tools-> import data -> select sql file-> select schema -> import) into your db. You can use Mysql workbench for it. As you said earlier, the schema name is 'openemis'

**Comment by Fuseteam** [comment]
@janithRS thanks i got in
