### ISSUE TITLE
css styles missing

### ISSUE THREAD

**Issue by Fuseteam** [moe-lk/sis-php#145]
after initial setup  and importing of the table the login screen seems to miss css styles

**Comment by janithRS** [comment]
@Fuseteam Please add a descriptive issue with a screenshot. That way we could understand the problem and provide you with a solution easily

**Comment by Fuseteam** [comment]
@janithRS i'm not sure how much more descriptive i can be the css styles other than the css styles are missing
here's an screenshot
![image](https://user-images.githubusercontent.com/10421851/74936023-248ce700-53c8-11ea-8b87-1e3acce46cf3.png)

**Comment by janithRS** [comment]
Hmm.. Looks like you haven't enabled the apache rewrite mode, try this
https://stackoverflow.com/questions/869092/how-to-enable-mod-rewrite-for-apache-2-2
or if you are using the docker application this won't be a problem

**Comment by Fuseteam** [comment]
ah cool @janithRS, is there a specific place it needs to redirect to?

**Comment by Fuseteam** [comment]
ah found it thanks for the tip @janithRS
