### ISSUE TITLE
Password policy implementation

### ISSUE THREAD

**Issue by mohamednizar** [moe-lk/sis-php#153]
Enable force password at every three months and increase password strength.

**Comment by resha007** [comment]
in dev, working fine.

**Comment by resha007** [comment]
in stage, rules are ok. but only prompt in first login. if rejects in 1st login, never asks again. it works fine in dev.

**Comment by janithRS** [comment]
It's working correctly. Please check again. It's still directing to the
password change UI since we have not changed it yet.

**Comment by resha007** [comment]
no, i checked for several account. please try for this 1573387650(u/p) in stage.

**Comment by resha007** [comment]
in stage,password policy is ok.

**Comment by resha007** [comment]
niel sir asked that can we have an strength line for password when entering new password?
