### ISSUE TITLE
System support for withdrawn students

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#17]
withdrawan students are visible in the class

**Comment by mohamednizar** [comment]
@jeewana20  Enabled to delete students from the directory it self, we don;t need to withdrow before delete anymore, you can find the student from the directory by the ID and delete it. 

This will support only with one by one delete without giving multiple options for delete many records at one. Is this sufficient for work with the system for cleansing process ?

**Comment by jeewana20** [comment]
please do not close the issue until we confirm that it is resolved

**Comment by resha007** [comment]
there is no option to delete the withdrawn students.
![withdrwn delete](https://user-images.githubusercontent.com/45994536/72958442-439a5800-3dcd-11ea-9b62-4e8d202b8544.PNG)

**Comment by resha007** [comment]
404 error  when trying to delete enrolled students in prod
![delete](https://user-images.githubusercontent.com/45994536/72959522-9590ad00-3dd0-11ea-96fe-602884c8386d.PNG)
