### ISSUE TITLE
System bug- Edit button

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#18]
the edit button is not functional as you cannot add or edit the admission number

**Comment by mohamednizar** [comment]
The Admission number is align to the student's academic details, so we can edit on academic information tab.

Follow the given instruction bellow. 
![Screenshot from 2019-10-01 15-36-30](https://user-images.githubusercontent.com/8711284/65953375-71940f00-e461-11e9-87ae-ee0d1d1a1ca1.png)
![Screenshot from 2019-10-01 15-36-40](https://user-images.githubusercontent.com/8711284/65953374-71940f00-e461-11e9-8635-10caa48501ae.png)
![Screenshot from 2019-10-01 15-37-09](https://user-images.githubusercontent.com/8711284/65953373-71940f00-e461-11e9-89d7-0f310e95c9e7.png)
![Screenshot from 2019-10-01 15-37-24](https://user-images.githubusercontent.com/8711284/65953371-70fb7880-e461-11e9-8ca4-c160161dfdb9.png)

**Comment by jeewana20** [comment]
checked in dev site. seems ok

**Comment by mohamednizar** [comment]
There are no any code commit for this.

**Comment by jeewana20** [comment]
Please confirm this is incorporated into the production.

**Comment by mohamednizar** [comment]
@jeewana20 please follow the instructions  to confirm in the Prod
