### ISSUE TITLE
System bug-Deselect subjects

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#19]
Subjects cannot be deselected from certain grades in certain schools

**Comment by mohamednizar** [comment]
We can de-select subject after adding , if the school wan to remove some certain  subjects they need to delete them one by one.

Please follow the instructions given bellow.

**Navigate to Academic -> subjects**
![Screenshot from 2019-10-01 16-13-19](https://user-images.githubusercontent.com/8711284/65955788-845d1280-e466-11e9-99cf-914ddc7c0217.png)

**Filter the class that need to remove the subject**
![Screenshot from 2019-10-01 16-13-25](https://user-images.githubusercontent.com/8711284/65955789-84f5a900-e466-11e9-80b2-1ca52eda334c.png)

**From the actions select delete option**
![Screenshot from 2019-10-01 16-13-33](https://user-images.githubusercontent.com/8711284/65955792-84f5a900-e466-11e9-9250-ecbc184be4e9.png)

**In the delete menu confirm the delete oration by saving**
![Screenshot from 2019-10-01 16-13-39](https://user-images.githubusercontent.com/8711284/65955796-84f5a900-e466-11e9-9b99-7efd8ad1a6b6.png)

**See the deleted subject**
![Screenshot from 2019-10-01 16-13-44](https://user-images.githubusercontent.com/8711284/65955797-858e3f80-e466-11e9-8997-fe4b63014fce.png)

**Comment by jeewana20** [comment]
checked in dev site. seems ok

**Comment by mohamednizar** [comment]
There are no any code changes for this issue.

**Comment by jeewana20** [comment]
Please confirm whether this is done in production.

**Comment by mohamednizar** [comment]
@jeewana20 ,please follow the instruction in the production and confirm this.
