### ISSUE TITLE
Auto changed the school status

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#192]
on 23 rd of May someone has made an institution(06113) Inactive to Active with Admin privileges. We have not done any changes or log into the system during that time.Please see the screenshot with respect to last record.

![06113 - Inactive](https://user-images.githubusercontent.com/55229512/83121177-9bd0c600-a0ef-11ea-9bc8-a3c31c115c90.PNG)

**Comment by mohamednizar** [comment]
@resha007  Hope we don't have any kind of development in this issue. Can you confirm with School history?

**Comment by resha007** [comment]
i added a screenshot of history in previous comment.

**Comment by mohamednizar** [comment]
@resha007 did you change this back to active? Seems the admin user has did the changes, are we confident that none of us didn't make any changes via the import sheet or manual status update on this institution?

**Comment by resha007** [comment]
![image](https://user-images.githubusercontent.com/45994536/95943535-bb009380-0e03-11eb-9df7-0118d94116fc.png)

**Comment by jeewana20** [comment]
done by a user.
