### ISSUE TITLE
Email status Failed

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#194]
email status is failed in history and not received emails.
Ex: un: 1557379742
pw : zsxqtd 

![image](https://user-images.githubusercontent.com/55229512/85361960-ebfa4700-b53a-11ea-8db6-bb5d8ab2f2e1.png)
![image](https://user-images.githubusercontent.com/55229512/85362079-32e83c80-b53b-11ea-8151-2335c6e8f733.png)

**Comment by mohamednizar** [comment]
This is fixed and released on : https://github.com/moe-lk/bulk-upload/releases/tag/v1.2.5.2
