### ISSUE TITLE
age limit error

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#199]
there is an error with the age limit. one user uploaded a file with 2000/mm/dd bdays to 13arts(2) and they tried to upload students with 2000/mm/dd bdays and then failed.

and this occurred to special edu classes also.

**Comment by mohamednizar** [comment]
@resha007  what is the age limit for 13arts(2) ? can you replicate the scenario in the Dev environment, please?

**Comment by resha007** [comment]
there is an error with grades of dev. can we try this on uat?

**Comment by mohamednizar** [comment]
@resha007 can you replicate this issue in the dev or UAT?
