### ISSUE TITLE
Enable edit option for Nationalities and  ad more Sri Lankan ethnic groups in list

### ISSUE THREAD

**Issue by mohamednizar** [moe-lk/sis-php#2]
These are the list of nationalities/ethnicities in Sri Lanka. 
- [ ] Sinhalese 
- [ ] Sri Lankan Tamils
- [ ] Sri Lankan Moors
- [ ] Indian Tamils 
- [ ] Sri Lankan Malays 
- [ ] Burghers/Eurasian
- [ ] Indian Moors

In adition, the current options are listed as Sri Lankan BC, Sri Lankan NIC. during the data cleaning part, provide an option to update the nationalities for manual data entries.

**Comment by mohamednizar** [comment]
@jeewana20 In the dev environment the feature was implemented , please verify and confirm

**Comment by jeewana20** [comment]
Please confirm whether it is incorporated into dev or production.
