### ISSUE TITLE
System bug- Filters in the Directory

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#20]
All the users will be listed in the Directory even if the filter options are applied

**Comment by mohamednizar** [comment]
A fix added in dev environment, check the issue.

**Comment by jeewana20** [comment]
checked. it is working now

**Comment by jeewana20** [comment]
Is it implemented in production? please confirm

**Comment by mohamednizar** [comment]
@jeewana20 , No will update the prod during this weekend.

**Comment by resha007** [comment]
when click search, loading for a long time and "504 Gateway Time-out" error occured in prod.
