### ISSUE TITLE
Not updating admission number 

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#207]
in bulk upload, in update sheet, not updating the admission number at the system. no error shows in remarks.

**Comment by resha007** [comment]
in UAT or Dev?

**Comment by mohamednizar** [comment]
@resha007 did you try to test this again this UAT?

**Comment by resha007** [comment]
in UAT, status is success, but the admission number is not updated in the system.

**Comment by mohamednizar** [comment]
@resha007  shall check this again in UAT?

**Comment by resha007** [comment]
its working fine on UAT

**Comment by resha007** [comment]
we got this issue again.

1551853059
Af@lareef1
Census- 16279 
Grade 1
