### ISSUE TITLE
DS division not added

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#208]
when importing schools to the system with DS division, some errors are occurred.

![image](https://user-images.githubusercontent.com/45994536/87290615-d82f7880-c51b-11ea-82fa-40fcd8d9484d.png)

[NEMIS_SIS_Import_Institutions_Failed_1590644135 (2).xlsx](https://github.com/moe-lk/sis-php/files/4911639/NEMIS_SIS_Import_Institutions_Failed_1590644135.2.xlsx)

**Comment by mohamednizar** [comment]
@resha007  Did you test this in UAT ?

**Comment by resha007** [comment]
this was fixed
