### ISSUE TITLE
unable to click on Delete button on small screens

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#272]
users have to scroll horizontally to click on the delete button in small sized screens. when they scrolled and clicked on it, automatically scrolls back to the initial state.

**Comment by jeewana20** [comment]
we can remove exam related columns from the student list.

Taking G5 Exam | Income At G5 | Taking Ol Exam | Taking Al Exam

**Comment by janithRS** [comment]
Noted. Working on it

**Comment by resha007** [comment]
this was fixed in uat.
