### ISSUE TITLE
NSID name swapping - Restrict DoE update

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#279]
in 17529 school,

**4KF-MGD-QJW** - JAYASINGHE ARACHCHILAGE MALEESHA SATHSARA J.A.M.SATHSARA - this student actually should be in grade 5 in 2019. but he is in grade 4 on the system. (system saying that this record cant be deleted due to doe related. he didnt face the G5 exam in 2020)
created : November 28, 2019 - 10:14:37
modified : October 09, 2020 - 12:06:38

in our exam sheet,
**4KF-MGD-QJW** - WEDIPPULI   ARACHCHILAGE DILINDU SAMAN KUMARA - this student is the real student in grade 4 who face G5 exam in the same school.

in the system : 
**A13011576572186** - WEDIPPULI ARACHCHILAGE DILIDU SAMAN KUMARA
created : December 17, 2019 - 08:43:06
modified : October 09, 2020 - 03:34:00

**Comment by mohamednizar** [comment]
@resha007 can find the information related to this student in the DoE data file ?

**Comment by resha007** [comment]
![image](https://user-images.githubusercontent.com/45994536/95970849-0def4080-0e2e-11eb-8e2c-fe7228e9503e.png)

**Comment by mohamednizar** [comment]
@resha007  from the finding, the student's name has been altered by the School since we only prevent delete of DoE data, we may need to restrict update too.

**Comment by resha007** [comment]
instructed them to update correct name.

**Comment by resha007** [comment]
decided to not giving edit option(DoE entered data) for normal users, and those changes done through the admin login.
