### ISSUE TITLE
Institution/class swapping issue - DoE entered data

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#282]
in 22154(Kukurampola junior college) school, there is a student - 99W-T38-RQY in grade 4. (entered through DoE data).
![image](https://user-images.githubusercontent.com/45994536/96215887-c20ed980-0f9c-11eb-9c76-fbdec8a0841d.png)

in academic -> classes -> institution is 21271(PIYARAPANDOWA VIDYALAYA).
![image](https://user-images.githubusercontent.com/45994536/96215908-cf2bc880-0f9c-11eb-92d4-50de41ed3ac7.png)

Then 21271 -> academic -> classes -> grade 1(only one class).
![image](https://user-images.githubusercontent.com/45994536/96216084-19ad4500-0f9d-11eb-9283-5abc049892d4.png)

there are 756 grade 4 students in this class.
![image](https://user-images.githubusercontent.com/45994536/96216145-38134080-0f9d-11eb-9ad5-ce390d8039f6.png)
![image](https://user-images.githubusercontent.com/45994536/96216155-3ba6c780-0f9d-11eb-8625-c53d8d2fc1c9.png)

**Comment by mohamednizar** [comment]
@resha007  can you check this issue too ?

**Comment by resha007** [comment]
institution of class has been fixed. but in the 2nd school (21271), there are 756 grade 4 students in grade 1 class.

**Comment by mohamednizar** [comment]
@resha007 can you check number of students in UAT of  school   21271 ?

**Comment by resha007** [comment]
this was fixed.

**Comment by resha007** [comment]
when entering DoE data to sis(to generate NSID for G5 exam - 2020) as grade 4(2019) students, number of students were placed on wrong schools due to census number(moe) vs school id(doe) mismatching issue.
