### ISSUE TITLE
Pending Admission students are not promoted

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#299]
there is a mismatch between count in Institution->Students and the count in pending admission->done(approved). #15 

in 02242 school, the students who are not appearing in Institution->Students (those who are appearing in pending admission->done(approved)) are not promoted to YR2020.

**Comment by mohamednizar** [comment]
in wich Grade ?

**Comment by resha007** [comment]
every grade.

[nemis screen shot.zip](https://github.com/moe-lk/sis-php/files/5581393/nemis.screen.shot.zip)

**Comment by nshamit** [comment]
students are displayed in pending admission, not in approved status. 
- we need to identify these students, move them to approved status, and make sure the counts are reconciled.

**Comment by resha007** [comment]
those students cant manual promotion. have to find another solution.

![image](https://user-images.githubusercontent.com/45994536/115678983-b945f880-a36f-11eb-8194-35da4f33f88c.png)

**Comment by HarindaVithana** [comment]
Non-approved records were not found in the mentioned schools. Other Pending students have to be approved manually

**Comment by resha007** [comment]
Those students are approved, but there is a count difference. 

**All approved - 3566** (Students -> pending admission -> done)

YR2018/2019 -  202
YR2019/2020 -  221
YR2020          - 1940
**Total               - 2363**

difference = 3566 - 2363 = **1203**

Those 1203 students are not listed in Institutions -> Students.
