### ISSUE TITLE
cant demote from 6 to 5

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#316]
unable to demote students from level to another level. 
ex : lower secondary to primary.

**Comment by mohamednizar** [comment]
@resha007 Added a fix to the UAT, You can verify it.

**Comment by resha007** [comment]
still having the issue.
![image](https://user-images.githubusercontent.com/45994536/104426596-25aea000-55a8-11eb-8b55-3533dfabcd4b.png)

**Comment by resha007** [comment]
now its fixed. but the 1st grade of the level is not shown.(small issue)
can deploy to prod.


ex : grade 1 not displayed in the list.
![image](https://user-images.githubusercontent.com/45994536/104431511-0450b280-55ae-11eb-8036-cc6b4cd23b41.png)

**Comment by mohamednizar** [comment]
@resha007 Deployed to the prod

**Comment by resha007** [comment]
fixed on prod
![image](https://user-images.githubusercontent.com/45994536/104436264-665fe680-55b3-11eb-98b3-e5f904f5215e.png)
