### ISSUE TITLE
not promoted, 2020 to 2021

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#340]
ADAIKALA ANNAI VIDYALAYA(13085) student are not promoted to 2021 academic year

**Comment by HarindaVithana** [comment]
Needed help from Nizar to resolve promotion issues

**Comment by HarindaVithana** [comment]
Promotion Script has written and uploaded for reviewing by Nizar

**Comment by HarindaVithana** [comment]
Check the students data to find problems in auto promotion.

**Comment by resha007** [comment]
13085 school is promoted, but 2 students left in YR2020 and 11 students in YR2019

**Comment by resha007** [comment]
2 students in YR2020 - 13 intermediate pool
11 students in YR2019 - grade 11
