### ISSUE TITLE
Enable Text and "/" for admission number 

### ISSUE THREAD

**Issue by mohamednizar** [moe-lk/sis-php#4]
Currently, the admission number is only allowed to add a number, we need to allow them to type admission number like 2019/AS/G3/1235

**Comment by mohamednizar** [comment]
@resha007 the fix added for SIS application dev, hope we need to do the same for Bulk upload as well ?

**Comment by jeewana20** [comment]
this is not working

**Comment by resha007** [comment]
in dev, "/" and text is required to complete.

**Comment by resha007** [comment]
now that option cannot be accessed.  
error : __clone method called on non-object
