### ISSUE TITLE
System support- 21038-404 error

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#55]
there is a message name "404 forbidden page not found " when logging to staff in academic.
census no. 21038 
school name = Dambarawa m.m
we have entered a fresh school coordinator but still the error is there.

**Comment by resha007** [comment]
1. log in to sis as principal or admin (21038)
2. go to in Institute -> staff

![404 error](https://user-images.githubusercontent.com/45994536/72886704-4b57ef00-3d30-11ea-8d1a-63cdb47773ee.PNG)

**Comment by mohamednizar** [comment]
@resha007 can you update the status ?

**Comment by jeewana20** [comment]
its fixed in prod

**Comment by jeewana20** [comment]
its fixed in UAT
