### ISSUE TITLE
Staff- end date assigned

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#70]
The end date of some staff members are auto-added as "2019/11/29" and they are not visible on the staff list. this is not assigned to the position but rather assigned to the teacher

**Comment by resha007** [comment]
![staff end date](https://user-images.githubusercontent.com/45994536/72886407-ca005c80-3d2f-11ea-8307-5ffa89172fb1.PNG)

school census no : 00114

**Comment by mohamednizar** [comment]
@jeewana20 ,can't they edit the end of assignment ?

**Comment by jeewana20** [comment]
no. you have to make a new position and assign it to the teacher

**Comment by mohamednizar** [comment]
@jeewana20 , we written a migration for update end of assignment of staffs, once it deployed to the demo you can verify with the reported school's information.

**Comment by nshamit** [comment]
- Once migration done Jan 29, Nizar will send email to Jeewana. 
- Jeewana needs to test with school IDs with the issue.

**Comment by mohamednizar** [comment]
@jeewana20 , @nshamit  we wrote migration for this, but we encounter an issue on running that migration in new stag, let us resolve it,after this there is no any additional steps needed for staff. They will re assinged to the there positions without editing them .

**Comment by resha007** [comment]
again reported an issue from 01005 school for staff end date

**Comment by resha007** [comment]
![image](https://user-images.githubusercontent.com/45994536/83223643-012cc180-a199-11ea-8068-87c6b0bd563b.png)
