### ISSUE TITLE
BULK Upload- Monaragala

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#74]
In monaragala zone, in Grafana shows that the schools that have not started bulk upload process are shown as they have bulk uploaded

**Comment by mohamednizar** [comment]
@resha007 can you check the status of this school again?

**Comment by mohamednizar** [comment]
@jeewana20 can you send me more details on this issue to my email?

**Comment by mohamednizar** [comment]
@resha007  can you confirm this and close ?
