### ISSUE TITLE
Student- inability to add January born

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#83]
The system refuses to add January born students

**Comment by mohamednizar** [comment]
@jeewana20 , @nshamit , this issue fixed and deployed to the Production

**Comment by jeewana20** [comment]
we have uploaded a file and still waiting the reply email. when the reply email is received we will confirm

**Comment by resha007** [comment]
we are not able to check this because reply emails are not receiving in dev

**Comment by resha007** [comment]
this was tested in dev and it is ok now.
