### ISSUE TITLE
[Message Not Found] in field names

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#85]
![1](https://user-images.githubusercontent.com/45994536/71609446-8beb9f00-2bae-11ea-8b10-89ab5739b140.PNG)
in dev, in promotion, there is "[Message Not Found]" as field names.

**Comment by mohamednizar** [comment]
@resha007  ,The issue was fixed in dev, Please check in confirm this.

**Comment by resha007** [comment]
this is fixed in dev
