### ISSUE TITLE
Last field of Promotion is disabled

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#86]
in dev, in promotion, the last field is disabled by default. it activates only when change the previos dropdown twice.
![3](https://user-images.githubusercontent.com/45994536/71615178-eb10da00-2bd5-11ea-9c95-363e36c3fb6e.PNG)

**Comment by mohamednizar** [comment]
This field only enabled if the school has configure next grade for next academic year, please do the test in that view.

**Comment by resha007** [comment]
created classes in next academic year, but the field is disabled yet.
