### ISSUE TITLE
Auto changed the gender

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#88]
auto changed the gender to Female of students who are entered through the online system(no any bulk upload interaction).

**Comment by resha007** [comment]
@mohamednizar as you said, i checked the school for if there any bulk upload files in history. but there is no any bulk upload, but the gender has changed to Female.

**Comment by jeewana20** [comment]
for cleansing, we need to change the gender.

**Comment by mohamednizar** [comment]
@resha007 , There are bulkupload files related to changed data, we can reprocess either re-upload with correct gender data on this situation.
