### ISSUE TITLE
Delete option for duplicated studetns

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#90]
an option to delete students from schools who has been entered twice to the system.

**Comment by resha007** [comment]
directory search is not working properly in prod

**Comment by mohamednizar** [comment]
@resha007 , can you check this in demo ?

**Comment by resha007** [comment]
in directory search, the result is "There are no records."

**Comment by resha007** [comment]
in dev and demo, in directory search, the result is "There are no records.". therefore cant test the permanent delete.

**Comment by resha007** [comment]
delete from student list and add again via "add student" is working in dev and demo.

**Comment by resha007** [comment]
permanent delete is ok in dev

**Comment by resha007** [comment]
there is no option to delete withdrawn students from the list.

**Comment by resha007** [comment]
in stage,
permanent delete is working fine for principal.
in the soft delete(delete to change grade or class), deleted successfully(count reduced by 1), but after adding again,the student not added to student list (only appeared in pending admission under status "approved"). the count also not increased.

**Comment by resha007** [comment]
rechecked. in stage, permanent delete is working fine for principal.

**Comment by mohamednizar** [comment]
Fine, Let's introduce the feature to school
