### ISSUE TITLE
Pending emails to no process status

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#91]
in bulk upload, if the insert/update status in no process, the reply email should be sent.

**Comment by jeewana20** [comment]
#106

**Comment by jeewana20** [comment]
currently, there is no reply email is sent to the user when the files   show no process in history.

**Comment by mohamednizar** [comment]
@jeewana20 , email will only send to the user if we got properer success/ fail status by processing a file. From Sumedh's concer will teacher attend to update the status of file ?

**Comment by jeewana20** [comment]
can we send an email to the users who have files with "no process" status to go to history and click the correct file to be reprocessed.

**Comment by mohamednizar** [comment]
hmm, yes that can be done

**Comment by nshamit** [comment]
Notification to users w/ files that are not being processed will be done by Jan 30

**Comment by resha007** [comment]
this emails and reprocess button is working now.
