### ISSUE TITLE
Father/mother/guardian NIC invalid

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#92]
in bulk upload, even the NIC is correct, error shows that nic is invalid

**Comment by mohamednizar** [comment]
@resha007 , cn you share a spreadsheet to reproduce this bug please ?

**Comment by resha007** [comment]
[censusNo_className_sis_students_bulk_upload (17).xlsx](https://github.com/moe-lk/sis-php/files/4095820/censusNo_className_sis_students_bulk_upload.17.xlsx)

**Comment by jeewana20** [comment]
although Nizar said that the NIC contains only 9 digits in the format at yesterday's meeting we checked it today. I confirm that there are 10 digits in father's NIC number

**Comment by nshamit** [comment]
Ready for UAT by Jan 30th.

**Comment by mohamednizar** [comment]
@resha007 open is this still exist!
