### ISSUE TITLE
Grafana download class data, all fields

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#93]
a feature to download all the fields of the students by school in school dashboard.

**Comment by nshamit** [comment]
@mohamednizar to give KT to Imal to handle this.

**Comment by mohamednizar** [comment]
@nshamit  , informations are shared with @anjilo27 and he is working on it.

**Comment by mohamednizar** [comment]
@anjilo27 , did you manage to do this task?

**Comment by anjilo27** [comment]
I am working on it.

**Comment by anjilo27** [comment]
@mohamednizar I have a question to get student all subjects ( subject per column ). I write the query and it shows one subject in one column. Below I attached  the query. Now I want to span this to subject per column.

IFNULL(edus.name, 'NA') as `Subject 1`,
left join institution_subject_students iss on ist.id = iss.student_id
left join education_subjects edus on edus.id = iss.education_subject_id

**Comment by anjilo27** [comment]
Grafana All class data download query now uploaded to grafana and now it visible in school dashboard. (without admission No and DS division & I am working on it)
