### ISSUE TITLE
Fullname is limited for 100 characters (Feb 1)

### ISSUE THREAD

**Issue by resha007** [moe-lk/sis-php#94]
in bulk upload, the full name is limited to 100 characters. a feature to be created for the students who has more than 100 characters in their names.

**Comment by nshamit** [comment]
Options are - change to 250 characters
- use middle name and check if this prints out correctly, in order.

**Comment by janithRS** [comment]
Referred to issue #58

**Comment by jeewana20** [comment]
it was decided that the middle name field to be used in these cases. however, when the full name is required the portion of the name appeared in the middle name field must also be there.
